# themes from https://github.com/alacritty/alacritty-theme

import = ["~/.config/alacritty/themes/tokyo-night.toml"]

[env]
TERM="alacritty"

[font]
normal = { family = "DankMono Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
size = 15

[window]
decorations = "Buttonless"
padding.x=5
padding.y=5
